# Generated by Django 5.0.3 on 2024-05-04 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filieres', models.CharField(max_length=100)),
                ('date_inscriptions', models.DateField()),
                ('heure_inscriptions', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('promo', models.CharField(max_length=20)),
                ('filiers', models.CharField(default='', max_length=100)),
                ('annees', models.DateField(default='2022-05-21')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_inscriptions', models.DateField()),
                ('Annees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInscriptions.annees')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInscriptions.etudiant')),
            ],
        ),
    ]
